---
title: Accounts Payable Context
---
graph
  INVOICE---VENDOR
  INVOICE---WORKORDER[WORK ORDER]
  INVOICE---PURCHASEORDER[PURCHASE ORDER]
  INVOICE---PROJECT
  INVOICE---BILL
  BILL---PAYMENT
  BILL---LIENWAIVER[LIEN WAIVER]
  PAYMENT---VENDOR
  PURCHASEORDER---VENDOR  
  WORKORDER---VENDOR
  PROJECT---VENDOR
  LIENWAIVER---VENDOR