---
title: Construction Context
---
graph
  CONTRACT---VENDOR
  CONTRACT---CUSTOMER
  CUSTOMER---LOCATION
  CUSTOMER---PURCHASEORDER[PURCHASE ORDER]
  CUSTOMER---INVOICE
  PURCHASEORDER---PROJECT
  PURCHASEORDER---INVOICE
  INVOICE---VENDOR
  INVOICE---CUSTOMER
  LOCATION---PROJECT
  LOCATION---ASSET
  ASSET---WARRANTY
  WARRANTY---VENDOR
  WARRANTY---LOCATION
  PURCHASEORDER---VENDOR
  PROPOSAL---ESTIMATE
  ESTIMATE---PROJECT
  PROJECT---WORKORDER[WORK ORDER]
	PROJECT---TASK
  PROJECT---SUPERVISOR
  PROJECT---CHANGEORDER[CHANGE ORDER]
  PROPOSAL---CUSTOMER
  PROPOSAL---VENDOR
