---
title: Construction Context
---

flowchart LR

%% -----------------------------
%% Commercial Documents
%% -----------------------------
subgraph CommercialDocsCtx["Commercial&nbsp;Documents"]
  ESTIMATE
  PROPOSAL
end

%% -----------------------------
%% Customer & Contract Context
%% -----------------------------
subgraph CustomerCtx["Customer & Contract Context"]

    CUSTOMER
    CONTRACT
    LOCATION
end

%% -----------------------------
%% Procurement, Vendor, Install Base & Work Quality
%% -----------------------------
subgraph ProcurementCtx["Procurement, Vendor, Install Base & Work Quality"]

    PURCHASE_ORDER["PURCHASE ORDER"]
    INVOICE
    ASSET
    WARRANTY
    VENDOR
end

%% -----------------------------
%% Construction Execution
%% -----------------------------
subgraph ExecCtx["Construction Execution"]

    PROJECT
    CHANGE_ORDER["CHANGE ORDER"]
    TASK
    WORK_ORDER["WORK ORDER"]
    SUPERVISOR
end

%% -----------------------------
%% Relationships
%% -----------------------------
CUSTOMER --- CONTRACT
CUSTOMER --- LOCATION
CUSTOMER --- PURCHASE_ORDER
CONTRACT --- LOCATION

PURCHASE_ORDER --- INVOICE
PURCHASE_ORDER --- ASSET
PURCHASE_ORDER --- VENDOR
PURCHASE_ORDER --- WARRANTY

ASSET --- WARRANTY

LOCATION --- PROJECT
PURCHASE_ORDER --- PROJECT

PROJECT --- CHANGE_ORDER
PROJECT --- TASK
PROJECT --- WORK_ORDER
PROJECT --- SUPERVISOR

WARRANTY --- VENDOR
INVOICE --- VENDOR

ASSET --- LOCATION

CUSTOMER --- PROPOSAL
VENDOR --- PROPOSAL
PROJECT --- PROPOSAL
LOCATION --- PROPOSAL
ESTIMATE --- PROPOSAL
