---
title: Facilities Context
---
flowchart LR

%% CUSTOMER & COMMERCIALS
subgraph Comm["Customer & Commercials"]
  direction TB
  CUST[CUSTOMER]
  CONT[CONTRACT]
  PO["PURCHASE ORDER"]
  INV[INVOICE]
  PROP[PROPOSAL]

  CUST --- CONT
  CUST --- PO
  PO --- INV
  CUST --- PROP
end

%% EXECUTION
subgraph Exec["Execution&nbsp;(Programs&nbsp;&amp;&nbsp;Work&nbsp;Orders)"]
  direction TB
  PROG[PROGRAM]
  WO[WORK ORDER]

  PROG --- WO
end

%% LOCATION
subgraph LocBox["Location"]
  direction TB
  LOC[LOCATION]
end

%% INSTALL BASE & WORK QUALITY
subgraph Install["Install Base & Work Quality"]
  direction TB
  ASSET[ASSET]
  WARR[WARRANTY]

  ASSET --- WARR
end

%% VENDOR
subgraph VendBox["Vendor"]
  direction TB
  VEND[VENDOR]

  VEND --- WARR
  VEND --- PROP
end

%% CROSS-CUTTING RELATIONSHIPS

CUST --- LOC
LOC --- PROG
WO --- LOC

LOC --- ASSET
LOC --- VEND

CONT --- LOC
CONT --- VEND

WO --- PO
PO --- VEND

WO --- PROP
WO --- WARR
